function correctedKey = checkLineStyle( styleKey )
% check that the ''styleKey'' is one of the following keywords: 
%   ''straight'', ''singlearrow'', ''doublearrow'', ''straighttextbox'',
%   ''doublestraighttextbox'', ''singlearrowtextbox'',
%   ''doublearrowtextbox'' 

defaultKey = 'straight';
styleKeyIsValid = ischar( styleKey ) && ( ...
    strcmpi( styleKey, 'straight' ) || ...
    strcmpi( styleKey, 'singlearrow' ) || ...
    strcmpi( styleKey, 'doublearrow' ) || ...
    strcmpi( styleKey, 'straighttextbox' ) || ...
    strcmpi( styleKey, 'doublestraighttextbox' ) || ...
    strcmpi( styleKey, 'singlearrowtextbox' ) || ...
    strcmpi( styleKey, 'doublearrowtextbox' ) );
if ~styleKeyIsValid
    % throw a warning and set default key to ''straight''
    warning( ... 
        'SchematicTools:Line:illegalKeyword', ...
        ['style key must be a char array and it takes the following values: ', ...
         'straight, ', ...
         'singlearrow, ', ...
         'doublearrow, ', ...
         'straighttextbox, ', ...
         'doublestraighttextbox, ', ...
         'singlearrowtextbox, ', ...
         'doublearrowtextbox'] );
     % straight is assumed ...
else
    defaultKey = lower( styleKey );
end

correctedKey = defaultKey;