function colorkey = checkColorSpec( somePropertyCell )
colorkey = [];
n = length( somePropertyCell );
assert( mod(n,2) == 0, ...
    'SchematicTools:Static:illegaltype', ...
    'dimension of the supplied input must be a multiple of 2!');
for k = 1 : n/2
    keyhits = ...
        ischar( somePropertyCell{ 2 * k - 1 } ) && ...
        strcmpi( somePropertyCell{ 2 * k - 1 }, 'color' );
    if keyhits, colorkey = somePropertyCell{ 2 *k }; break; end
end