function correctedKey = checkCircleStyle( styleKey )
% check that the ''styleKey'' is one of the following keywords:
%    ''circle'', ''arc'', ''counterclockeddy'', ''clockeddy''

defaultKey = 'circle';
styleKeyIsValid = ischar( styleKey ) && ( ...
    strcmpi( styleKey, 'circle' ) || ...
    strcmpi( styleKey, 'arc' ) || ...
    strcmpi( styleKey, 'counterclockeddy' ) || ...
    strcmpi( styleKey, 'clockeddy' ) );
if ~styleKeyIsValid
    % throw a warning and set default key to ''circle''
    warning( ...
        'SchematicTools:Circle:illegalKeyword', ...
        ['style key must be a char array and take the following values: ', ...
        '''circle'', ', ...
        '''arc'', ', ...
        '''counterclockeddy'', ', ...
        '''clockeddy'''] );
else
    defaultKey = lower( styleKey );
end

correctedKey = defaultKey;