function [stringcell, datafile] = outputstream( obj )
% returns a cell-array of the main components of the current obj. This is
% used by its parent to auto-generate the code on a separate .m ...


% there is no data to load ... 
datafile = [];
stringhead = { [obj.name, ' = SchematicCircle( canvas, ', Schematic2D.staticgetstringasoutput(obj.style), ', ...' ] };
% attach property name ...
prop = obj.CurrentPropertyCell;
num  = length( prop );
propcell = cell(1, num/2);
propstringprefix =  '    ';
propstringaftfix = ', ...';
for k = 1 : num / 2 - 1
    propcell{ k } = [ propstringprefix, ...
        Schematic2D.staticgetstringasoutput( prop{ 2 * k - 1 } ), ', ', ...
        Schematic2D.staticgetstringasoutput( prop{ 2 * k } ), propstringaftfix ];
end
k = num / 2;
propcell{ num / 2 } = [ propstringprefix, ...
        Schematic2D.staticgetstringasoutput( prop{ 2 * k - 1 } ), ', ', ...
        Schematic2D.staticgetstringasoutput( prop{ 2 * k } ), ');' ];
string00   = { [obj.name, '.name = ', Schematic2D.staticgetstringasoutput( obj.name ), ';'] };
% set fillCircle ... 
string01   = { [ obj.name, '.fillCircle = ', Schematic2D.staticgetstringasoutput( obj.fillCircle ), ';'] };

% set fillColor ... 
string02   = { [ obj.name, '.setFillColor(', Schematic2D.staticgetstringasoutput( obj.fillColor ), ');'] };

% set sampling siize 
string03   = { [ obj.name, '.setSamplingSize(', Schematic2D.staticgetstringasoutput( obj.SampleSize ), ');'] };

% set position, radius, initial polar, final polar and head size ... 
string04 = ' ';
if ~isempty( obj.position ) && ~isempty( obj.radius )
    substring01 = { [ obj.name, '.setCircleGeometry( ... '] };
    substring02 = { ...
        [propstringprefix, Schematic2D.staticgetstringasoutput( obj.position ), ', ...'], ...
        [propstringprefix, Schematic2D.staticgetstringasoutput( obj.radius   ), ', ...'], ...
        [propstringprefix, Schematic2D.staticgetstringasoutput( obj.StartPolarAngle ), ', ...'], ...
        [propstringprefix, Schematic2D.staticgetstringasoutput( obj.EndPolarAngle ), ', ...'], ...
        [propstringprefix, Schematic2D.staticgetstringasoutput( obj.headproportion ), ');'] };
    string04 = [substring01, substring02];
end
string05 = { [ obj.name, '.draw();'] };
stringcell = [stringhead, propcell, string00, string01, string02, string03, string04, string05];
