classdef SchematicKeyMap < handle & matlab.mixin.SetGet
    properties(SetAccess = private, Hidden)
        parent;
    end
    properties(SetAccess = private, Hidden)
        % 1. these keys are mode independent ... 
        modeSelector                    =      'q'; 
        deleteLastObj                   =      'n';
        deleteAllObj                    =      'm';
        toggleInprecision               =      'i';
        togglePrintCoord                =      'o';
        outputContentToMatlabScript     =      'j';
        destroyImportedImage            =      'v';
        correctStackOrder               =      'b';
        customZoomIn                    =      '2';
        customZoomOut                   =      '3';
        customZoomReset                 =      '4';
        closeCanvas                     =      '0';
        % 14
        % 'normal' mode 
        saveGuidePointsToFile           =      's';
        deleteLastGuidePoint            =      'd';
        deleteAllGuidePoints            =      'a';
        computeGuideCurve               =      'r';
        bringUpCurvePropertyPanel       =      'u';
        toggleXLock                     =      'z';
        toggleYLock                     =      'x';
        % 22
        % 'selection' mode
        saveSelectedRegionToImage       =      's';
        translateSelectedObjectsRight   =      'd';
        translateSelectedObjectsLeft    =      'a'; 
        translateSelectedObjectsDown    =      'c';
        translateSelectedObjectsUp      =      'e';
        toggleSaveAsPDFFlag             =      'y';
        % 29
        % 'text' and 'arrowtext' mode
        resetTemporaryTextHolder        =      'a';
        bringUpTextEditor               =      'u';
        % 32
        % 'circle' insertion mode
        resetTemporaryCircleHolder      =      'a';
        bringUpCirclePropertyPanel      =      'u';
        % 35
        % 'atomic' selection mode
        rotateAntiClockWiseOrScaleDown  =      'a';
        rotateClockWiseOrScaleUp        =      'd';
        toggleBetweenRotOrScale         =      'w';
        deleteSelectedObject            =      'c';
        % 40
        % 'image' mode
        toggleCalibrationMode           =       'c';
        saveDataPointToFile             =       's';
        traceCurve                      =       'r';
        bringUpImagePropertyPanel       =       'u';
        deleteLastCalibrationPoint      =       'd';
        deleteLastDataPoint             =       'f';
        deleteAllDataPoint              =       'a';
        toggleSaveAutoGenData           =       't';
        toggleSetTerminationPt          =       'z';
        deleteTerminationPoint          =       'x';
    end
    properties(SetAccess = private, Hidden)
        %% uicomponents that provide an interactive key-assigning operation
        
        % listeners for the 'PostSet' event
        dynamicTextListeners;
        
        % static text components
        staticUITextComponents;
        
        % editable text components
        dynamicUITextComponents;
        
        % ui-figure to facilitate the key-assignemnt ...
        assignmentPanel;
        
        %
        updateKeyUIComponent;
        
        % name-list and name-value
        namelist;
        nameValue;
    end
    methods
        function obj = SchematicKeyMap( Parent )
            assert( isa( Parent, 'Schematic2D' ), ...
                'SchematicTools:Canvas:illegaltype', ...
                'Map must be initialized with a valid instance of the ''Schematic2D'' class!');
            obj.parent = Parent;
            
            % create the containers for the various components ...
            obj.dynamicTextListeners    = GeneralManager();
            obj.staticUITextComponents  = GeneralManager();
            obj.dynamicUITextComponents = GeneralManager();
            
            % resolve the property-cells
            obj.resolvePropertyCell();
        end
    end
    methods(Access = private)
        function resolvePropertyCell( obj )
            obj.namelist = { ...
                'modeSelector', ...
                'deleteLastObj', ...
                'deleteAllObj', ...
                'toggleInprecision', ...
                'togglePrintCoord', ...
                'outputContentToMatlabScript', ...
                'destroyImportedImage', ...
                'correctStackOrder', ...
                'customZoomIn', ...
                'customZoomOut', ...
                'customZoomReset', ...
                'closeCanvas', ...
                'saveGuidePointsToFile', ...
                'deleteLastGuidePoint', ...
                'deleteAllGuidePoints', ...
                'computeGuideCurve', ...
                'bringUpCurvePropertyPanel', ...
                'toggleXLock', ...
                'toggleYLock', ...
                'saveSelectedRegionToImage', ...
                'translateSelectedObjectsRight', ...
                'translateSelectedObjectsLeft', ...
                'translateSelectedObjectsDown', ...
                'translateSelectedObjectsUp', ...
                'toggleSaveAsPDFFlag', ...
                'resetTemporaryTextHolder', ...
                'bringUpTextEditor', ...
                'resetTemporaryCircleHolder', ...
                'bringUpCirclePropertyPanel', ...
                'rotateAntiClockWiseOrScaleDown', ...
                'rotateClockWiseOrScaleUp', ...
                'toggleBetweenRotOrScale', ...
                'deleteSelectedObject', ...
                'toggleCalibrationMode', ...
                'saveDataPointToFile', ...
                'traceCurve', ...
                'bringUpImagePropertyPanel', ...
                'deleteLastCalibrationPoint', ...
                'deleteLastDataPoint', ...
                'deleteAllDataPoint', ...
                'toggleSaveAutoGenData', ...
                'toggleSetTerminationPt', ...
                'deleteTerminationPoint'};
            % list of 'key' values 
            obj.nameValue = { ...
                obj.modeSelector, ...
                obj.deleteLastObj, ...
                obj.deleteAllObj, ...
                obj.toggleInprecision, ...
                obj.togglePrintCoord, ...
                obj.outputContentToMatlabScript, ...
                obj.destroyImportedImage, ...
                obj.correctStackOrder, ...
                obj.customZoomIn, ...
                obj.customZoomOut, ...
                obj.customZoomReset, ...
                obj.closeCanvas, ...
                obj.saveGuidePointsToFile, ...
                obj.deleteLastGuidePoint, ...
                obj.deleteAllGuidePoints, ...
                obj.computeGuideCurve, ...
                obj.bringUpCurvePropertyPanel, ...
                obj.toggleXLock, ...
                obj.toggleYLock, ...
                obj.saveSelectedRegionToImage, ...
                obj.translateSelectedObjectsRight, ...
                obj.translateSelectedObjectsLeft, ...
                obj.translateSelectedObjectsDown, ...
                obj.translateSelectedObjectsUp, ...
                obj.toggleSaveAsPDFFlag, ...
                obj.resetTemporaryTextHolder, ...
                obj.bringUpTextEditor, ...
                obj.resetTemporaryCircleHolder, ...
                obj.bringUpCirclePropertyPanel, ...
                obj.rotateAntiClockWiseOrScaleDown, ...
                obj.rotateClockWiseOrScaleUp, ...
                obj.toggleBetweenRotOrScale, ...
                obj.deleteSelectedObject, ...
                obj.toggleCalibrationMode, ...
                obj.saveDataPointToFile, ...
                obj.traceCurve, ...
                obj.bringUpImagePropertyPanel, ...
                obj.deleteLastCalibrationPoint, ...
                obj.deleteLastDataPoint, ...
                obj.deleteAllDataPoint, ...
                obj.toggleSaveAutoGenData, ...
                obj.toggleSetTerminationPt, ...
                obj.deleteTerminationPoint};
        end
        function keyValCallback(obj, ~, ~, id, p)
            % only assignment the first char
            if length( p.String ) < 1
                warning( ...
                    'SchematicTools:keyReassignment:incorrectDim', ...
                    'invalid key!' );
                return;
            end
            obj.nameValue{ id } = p.String(1);
        end
        
        function updateMap( obj, ~, ~ )
            % uses the 'set' method to reset the map
            numberOfProp = length( obj.namelist );
            namelist_    = obj.namelist;
            namevalue    = obj.nameValue;
            for k = 1 : numberOfProp
                set(obj, namelist_{ k }, namevalue{ k } );
            end
            if ~isempty( obj.assignmentPanel ), set( obj.assignmentPanel, 'visible', 'off' ); end
        end
    end
    methods(Hidden)
        initializeCompt( obj );
    end
end