function internalPropertyStructInitialization( obj )
% create the pred-defined property structures associated with each of the
% tmp object holders of the canvas ... 

obj.propertyShapeStruct = struct( ...
    'style', 'open', ...           % 
    'fillShape', false, ...        % 
    'fillColor', 'b', ...          %
    'facealpha',   1, ...
    'color', 'b',    ...           % 
    'linewidth', 1.2, ...          %
    'linestyle', '-.', ...
    'name',       '');           %

% next define the text buffer object 
obj.propertyTextStruct = struct( ...
    'style', 'straighttextbox', ...  % dummy
    'color', 'none', ...             % dummy
    'width',  .07, ...               % width    
    'height', .03, ...               % height 
    'textcolor', 'k', ...            % this is important as well
    'backgroundcolor', 'none', ...
    'edgecolor', 'none', ...
    'fontsize', 17, ...
    'name',   '');

% next, arrowtext buffer object 

obj.propertyArrowTextStruct = struct( ...
    'style', 'singlearrowtextbox', ...
    'color', 'k', ...
    'linewidth', 1.2, ...
    'linestyle', '-', ...
    'width',  .07, ...
    'height', .03, ...
    'textcolor', 'k', ...
    'backgroundcolor', 'w', ...
    'edgecolor', 'none', ...
    'fontsize', 17, ...
    'name',  '');

obj.propertyCircleStruct = struct( ...
    'style', 'circle', ...
    'color', 'k', ...
    'fillShape', false, ...
    'linewidth', 1.2, ...
    'linestyle', '-', ...
    'radius', .025, ...
    'ipolar', 0, ...
    'fpolar', 6.2832, ...
    'name',  '');
% initialize other property-related attributes ... 
obj.propertypanelstaticcomponents   = GeneralManager();
obj.propertypaneleditablecomponents = GeneralManager();
obj.propertycomptlisteners          = GeneralManager();