function internalImageSavingModeUICallback( obj, ~, ~ )

if obj.saveAutoGeneratedData
    set( obj.imageSavingModeUI, 'backgroundcolor', 'b', 'string', 'auto' );
else
    set( obj.imageSavingModeUI, 'backgroundcolor', 'r', 'string', 'manual');
end