function internalImageKeyPressed( obj, keypressed )

keyref = obj.keyMap;

switch keypressed
    case keyref.toggleCalibrationMode
        % toggles the calibration mode
        obj.isInCalibration = ~obj.isInCalibration;
    case keyref.saveDataPointToFile
        % save the data to file ...
        obj.internalBringContextureSaveWindow();
    case keyref.traceCurve
        % traceCurve
        obj.imager.automatetrace();
    case keyref.bringUpImagePropertyPanel
        % bring up the image property panel
        obj.imager.internalbringuppropertypanel();
    case keyref.deleteLastCalibrationPoint
        % f = 1, 2, 3, 4, 0 (1st, 2nd, 3rd, 4th) displayed
        if ~obj.isInCalibration, return; end
        f = obj.calibrationcount;
        if f ~= 0
            % current f = 1,2,3,4
            calipoint = obj.calibrationGuide.GetObjRef(f);
            calipoint.turn( 'off' );
            f = f - 1;
            obj.calibrationcount = f;
        end
    case keyref.deleteLastDataPoint
        obj.flushGuide(   'last' );
        obj.imager.flush( 'last' );
    case keyref.deleteAllDataPoint
        obj.flushGuide(   'all'  );
        obj.imager.flush( 'all'  );
        % reset the curve if it exists
        if ~isempty( obj.imager.curvehandle )
            set( obj.imager.curvehandle, 'visible', 'off' );
        end
    case keyref.toggleSaveAutoGenData
        % 
        obj.saveAutoGeneratedData = ~obj.saveAutoGeneratedData;
    case keyref.toggleSetTerminationPt
        % can only toggle if we are out of the calibration mode 
        if ~obj.isInCalibration
            obj.imageSettingTerminationPoint = ...
                ~obj.imageSettingTerminationPoint;
            if obj.imageSettingTerminationPoint
                % disable any previous anchors
                obj.terminationGuide.turn( 'off' );
            end
        end
    case keyref.deleteTerminationPoint
        % disable any termination 
        obj.terminationGuide.turn( 'off' );
        obj.imager.setTerminationPoint( [] );
end
