function internalEditableStringCallback( obj, ~, ~ )
% two things happen. One, we save the points in the container to an output
% file, specified by the 'string' property of the 'editableobj'

% secondly, we flush all guide points and set the 'visible' property to
% 'off' on the 'savepanel'


% we assume that 'editableobj' is non-empty 

string = obj.editableobj.String;

% concatenate string to create an effective filename

extensionType = '.dat';

filename = [ obj.workMdataPath, string, extensionType ];

% we do not check the correctness of the filename ... 
if obj.currentModeState == 7
    % this is in image-digitizer mode
    obj.imager.writeToOutputFile( filename, obj.saveAutoGeneratedData);
else
    % in normal mode ...
    obj.saveGuidePointsToFiles( filename );
end

% set the 'visible' state to 'off'

set( obj.savepanel, 'visible', 'off');
set( obj.editableobj, 'string', '');