function internalAddModeTextIdentifierPanel( obj )
% create an uicontrol object to identify the mode we are on.

obj.ModeIdentifierUi = uicontrol( ...
    obj.parent.Fig, ...
    'style', 'text', ...
    'units', 'normalized', ...
    'position', [.005, .98, .1, .02], ...
    'backgroundcolor', [.9, .9, .9], ...
    'fontsize', 10, ...
    'ForegroundColor', 'b', ...
    'string', obj.currentMode );

obj.CoordinateDisplay = uicontrol( ...
    obj.parent.Fig, ...
    'style', 'text', ...
    'units', 'normalized', ...
    'position', [.107, .98, .1, .02], ...
    'backgroundcolor', [.9, .9, .9], ...
    'fontsize', 10, ...
    'ForegroundColor', 'b', ...
    'string', '     ,      ' );

obj.figExportModeDisp = uicontrol( ...
    obj.parent.Fig, ...
    'style', 'text', ...
    'units', 'normalized', ...
    'position', [.209, .98, .1, .02], ...
    'backgroundcolor', [.0, .0, .0], ...
    'fontsize', 10, ...
    'ForegroundColor', 'w', ...
    'string', 'pdf' );
% add the listener for the 'saveasPDF' property ... 
obj.saveasPDFListener = addlistener(obj,'saveasPDF', 'PostSet', @obj.internalSaveAsPDFCallback);


% create the import static ui element
obj.importUIDisp = uicontrol( ...
    obj.parent.Fig, ...
    'style', 'pushbutton', ...
    'units', 'normalized', ...
    'position', [.311, .98, .1, .02], ...
    'backgroundcolor', 'r', ...
    'fontsize', 10, ...
    'ForegroundColor', 'g', ...
    'string', 'import', ...
    'callback', @obj.internalImportImageCallback);

% locks ... 
obj.xlockUIDisp = uicontrol( ...
    obj.parent.Fig, ...
    'style', 'text', ...
    'units', 'normalized', ...
    'position', [.0052, .955, .048, .02], ...
    'backgroundcolor', [.0, .0, 1.0], ...
    'fontsize', 10, ...
    'ForegroundColor', [.8, .8, .8], ...
    'string', 'xlock', ...
    'visible', 'off');
% y-lock
obj.ylockUIDisp = uicontrol( ...
    obj.parent.Fig, ...
    'style', 'text', ...
    'units', 'normalized', ...
    'position', [.0532, .955, .048, .02], ...
    'backgroundcolor', [1.0, .0, .0], ...
    'fontsize', 10, ...
    'ForegroundColor', [.8, .8, .8], ...
    'string', 'ylock', ...
    'visible', 'off');

obj.xlockListener = addlistener( obj, 'xlock', 'PostSet', @obj.internalxlockCallback);
obj.ylockListener = addlistener( obj, 'ylock', 'PostSet', @obj.internalylockCallback);

% key-assignment
obj.mapui = uicontrol( ...
    obj.parent.Fig, ...
    'style', 'pushbutton', ...
    'units', 'normalized', ...
    'position', [.413, .98, .1, .02], ...
    'backgroundcolor', 'b', ...
    'foregroundcolor', 'w', ...
    'fontsize', 10, ...
    'string', 'keys', ...
    'callback', @obj.internalAssignKeys);

% archive the xlim and ylim of the axes' object
obj.archivedXLim = obj.parent.Axs.XLim;
obj.archivedYLim = obj.parent.Axs.YLim;