function clockasstring = staticgetclockasstring()
% obtain the clock data as string in the format _xxxx_(x)x_(x)x_(x)x_(x)x
%                                                |    |     |    |    |
%                                               yr   mon   day  hr   min
% set format to shortg 
format shortg;
clockvec = clock();
clockasstring = [ '_', ...
    num2str( clockvec( 1 ) ), '_', ...
    num2str( clockvec( 2 ) ), '_', ...
    num2str( clockvec( 3 ) ), '_', ...
    num2str( clockvec( 4 ) ), '_', ...
    num2str( clockvec( 5 ) ) ];