function internalEvaluateClosedShape( obj )
% one evaluates the closed shape - a rather simple plot
%
xlim = obj.parent.parent.Axs.XLim;
ylim = obj.parent.parent.Axs.YLim;
defaultshape = obj.shape;
if isempty( defaultshape )
    defaultshape = plot( ...
        obj.parent.parent.Axs, ...
        obj.xRawData, ...
        obj.yRawData, ...
        'pickableparts', 'none', ...
        'visible', 'off', ...
        obj.currentPropertyCell{:} );
    obj.shape = defaultshape;
else
    set( defaultshape, 'xdata', obj.xRawData, 'ydata', obj.yRawData);
end
% for the fill command ... 
if obj.fillShape
    if ~isempty( obj.vectorOfPatches )
        obj.vectorOfPatches.delete();
    end
    obj.vectorOfPatches = fill( ...
        obj.parent.parent.Axs, ...
        obj.xRawData, ...
        obj.yRawData, ...
        obj.fillColor, ...
        'pickableparts', 'none', ...
        'facealpha', obj.faceAlpha);
    %
end

obj.parent.parent.aaxis( [xlim, ylim] );